openapi: 3.0.0
info:
  title: CloneWar
  description: A clone detection api
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local test server

paths:
  /:
    get:
      summary: Returns Hello World
      description: Hello World
      responses:
        default:
          description: A string
