package fr.uge.clonewar.backend.database;

import io.helidon.dbclient.DbClient;

import java.util.Objects;

/**
 * Represents an Artefact entity of the database.
 */
public class ArtefactTable {

  /**
   * Represents a Row of the Artefact entity.
   * @param jarName The artefact's name
   */
  public record ArtefactRow(String jarName) {
    public ArtefactRow {
      Objects.requireNonNull(jarName);
    }
  }

  private final DbClient dbClient;

  /**
   * Creates an instance of the entity.
   * @param dbClient The database connection
   */
  public ArtefactTable(DbClient dbClient) {
    Objects.requireNonNull(dbClient);
    this.dbClient = dbClient;
    createTable();
  }

  private void createTable() {
    dbClient.execute(exec -> exec.update("CREATE TABLE IF NOT EXISTS artefact(id integer, jarName VARCHAR, PRIMARY KEY(id))"))
        .exceptionally(t -> {
          System.err.println(t.getMessage());
          return null;
        }).await();
  }

  /**
   * Insert a row to the database.
   * @param artefact The row to be inserted
   * @return The id autogenerated by the database
   */
  public int insert(ArtefactRow artefact) {
    Objects.requireNonNull(artefact);
    return dbClient.execute(exec ->
            exec.query("INSERT INTO artefact(jarName) VALUES (?) RETURNING id", artefact.jarName)
        ).first()
        .map(row -> row.column("id").as(Integer.class))
        .await();
  }

}
